version: '3.8'
services:
  app:
    build: .
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://appuser:apppass@mysql:3306/appdb
      JWT_SECRET: ${JWT_SECRET}
      # Lokasi chrome default di image resmi puppeteer
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
    volumes:
      - ./storage/uploads:/app/storage/uploads
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0.36
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
# services:
#   app:
#     build: .
#     container_name: nextjs-app
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: mysql://appuser:apppass@mysql:3306/appdb
#       JWT_SECRET: supersecretkey # ubah jadi rahasia sendiri
#       BASE_URL: http://localhost:3000
#     volumes:
#       - ./storage/uploads:/app/storage/uploads
#     depends_on:
#       - mysql
#     networks:
#       - app-network # ⬅️ Tambahkan network

#   mysql:
#     image: mysql:8.0.36 # ✅ Versi stabil & kompatibel untuk CPU lama
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: appdb
#       MYSQL_USER: appuser
#       MYSQL_PASSWORD: apppass
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - app-network # ⬅️ Tambahkan network juga
# volumes:
#   mysql_data:

# networks:
#   app-network: # ⬅️ Definisi network
#     driver: bridge
