name: Deploy NextJS to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Masuk ke direktori
            cd /var/www/my-app
            
            # 1. Perbaikan Izin (Solusi Permission Denied & Dubious Ownership)
            sudo chown -R $USER:$USER .
            git config --global --add safe.directory /var/www/my-app
            
            # 2. Update Source Code
            git pull origin main
            
            # 3. Setup Folder & Environment
            mkdir -p storage/uploads
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
            
            # 4. Jalankan Docker (Menggunakan Docker Compose V2)
            sudo docker compose up -d --build
            
            # 5. Cleanup
            sudo docker image prune -f
# name: CI CD Next.js Docker

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#         #  github registry login
#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build Docker image
#         run: |
#           docker build -t ghcr.io/${{ github.repository }}:latest .

#       # Build and push the Docker image
#       - name: Push Docker image
#         run: |
#           docker push ghcr.io/${{ github.repository }}:latest

#       - name: Deploy to VPS via SSH
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           key: ${{ secrets.VPS_SSH_KEY }}
#           script: |
#             sudo /root/deploy.sh
